[package]
name = "day-3"
authors = ["Pablo Hernandez (@Hadronomy)"]
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.24.2"
itertools = "0.12.0"
miette = { version = "5.10.0", features = ["fancy"] }
nom = "7.1.3"
nom_locate = "4.2.0"
rstest = "0.18.2"
tracing = "0.1.40"
