[package]
name = "{{project-name}}"
authors = ["Pablo Hernandez (@Hadronomy)"]
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.0"
miette = { version = "5.10.0", features = ["fancy"] }
rstest = "0.18.2"
tracing = "0.1.40"
